
package org.iso8583.wsdl.validasi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "validasiPortType", targetNamespace = "urn:validasi")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ValidasiPortType {


    /**
     * validasidata
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:validasi#getData")
    @WebResult(partName = "return")
    public String getData(
        @WebParam(name = "id", partName = "id")
        String id);

}
