
package org.iso8583.wsdl.validasi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "validasi", targetNamespace = "urn:validasi", wsdlLocation = "http://localhost/bpkad/verifikasi/simpad-validasi.php?wsdl")
public class Validasi
    extends Service
{

    private final static URL VALIDASI_WSDL_LOCATION;
    private final static WebServiceException VALIDASI_EXCEPTION;
    private final static QName VALIDASI_QNAME = new QName("urn:validasi", "validasi");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/bpkad/verifikasi/simpad-validasi.php?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDASI_WSDL_LOCATION = url;
        VALIDASI_EXCEPTION = e;
    }

    public Validasi() {
        super(__getWsdlLocation(), VALIDASI_QNAME);
    }

    public Validasi(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDASI_QNAME, features);
    }

    public Validasi(URL wsdlLocation) {
        super(wsdlLocation, VALIDASI_QNAME);
    }

    public Validasi(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDASI_QNAME, features);
    }

    public Validasi(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Validasi(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidasiPortType
     */
    @WebEndpoint(name = "validasiPort")
    public ValidasiPortType getValidasiPort() {
        return super.getPort(new QName("urn:validasi", "validasiPort"), ValidasiPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidasiPortType
     */
    @WebEndpoint(name = "validasiPort")
    public ValidasiPortType getValidasiPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:validasi", "validasiPort"), ValidasiPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDASI_EXCEPTION!= null) {
            throw VALIDASI_EXCEPTION;
        }
        return VALIDASI_WSDL_LOCATION;
    }

}
