
package validasi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "verifikasiProxy", targetNamespace = "urn:validasi", wsdlLocation = "http://alfarios-macbook-pro.local:8280/services/verifikasiProxy?wsdl")
public class VerifikasiProxy
    extends Service
{

    private final static URL VERIFIKASIPROXY_WSDL_LOCATION;
    private final static WebServiceException VERIFIKASIPROXY_EXCEPTION;
    private final static QName VERIFIKASIPROXY_QNAME = new QName("urn:validasi", "verifikasiProxy");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://alfarios-macbook-pro.local:8280/services/verifikasiProxy?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VERIFIKASIPROXY_WSDL_LOCATION = url;
        VERIFIKASIPROXY_EXCEPTION = e;
    }

    public VerifikasiProxy() {
        super(__getWsdlLocation(), VERIFIKASIPROXY_QNAME);
    }

    public VerifikasiProxy(WebServiceFeature... features) {
        super(__getWsdlLocation(), VERIFIKASIPROXY_QNAME, features);
    }

    public VerifikasiProxy(URL wsdlLocation) {
        super(wsdlLocation, VERIFIKASIPROXY_QNAME);
    }

    public VerifikasiProxy(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VERIFIKASIPROXY_QNAME, features);
    }

    public VerifikasiProxy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VerifikasiProxy(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VerifikasiProxyPortType
     */
    @WebEndpoint(name = "verifikasiProxyHttpSoap11Endpoint")
    public VerifikasiProxyPortType getVerifikasiProxyHttpSoap11Endpoint() {
        return super.getPort(new QName("urn:validasi", "verifikasiProxyHttpSoap11Endpoint"), VerifikasiProxyPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerifikasiProxyPortType
     */
    @WebEndpoint(name = "verifikasiProxyHttpSoap11Endpoint")
    public VerifikasiProxyPortType getVerifikasiProxyHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("urn:validasi", "verifikasiProxyHttpSoap11Endpoint"), VerifikasiProxyPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns VerifikasiProxyPortType
     */
    @WebEndpoint(name = "verifikasiProxyHttpsSoap11Endpoint")
    public VerifikasiProxyPortType getVerifikasiProxyHttpsSoap11Endpoint() {
        return super.getPort(new QName("urn:validasi", "verifikasiProxyHttpsSoap11Endpoint"), VerifikasiProxyPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerifikasiProxyPortType
     */
    @WebEndpoint(name = "verifikasiProxyHttpsSoap11Endpoint")
    public VerifikasiProxyPortType getVerifikasiProxyHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("urn:validasi", "verifikasiProxyHttpsSoap11Endpoint"), VerifikasiProxyPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VERIFIKASIPROXY_EXCEPTION!= null) {
            throw VERIFIKASIPROXY_EXCEPTION;
        }
        return VERIFIKASIPROXY_WSDL_LOCATION;
    }

}
