
package verifikasilist;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "verifikasilistPortType", targetNamespace = "urn:verifikasilist")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface VerifikasilistPortType {


    /**
     * Get a listing of verifikasi
     * 
     * @param kodeBayar
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ISOMessage", action = "urn:ISOMessagelist#ISOMessage")
    @WebResult(partName = "return")
    public String isoMessage(
        @WebParam(name = "kode_bayar", partName = "kode_bayar")
        String kodeBayar);

}
