
package verifikasilist;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "verifikasilist", targetNamespace = "urn:verifikasilist", wsdlLocation = "http://localhost/bpkad/eRetribusi/verifikasi.php?wsdl")
public class Verifikasilist
    extends Service
{

    private final static URL VERIFIKASILIST_WSDL_LOCATION;
    private final static WebServiceException VERIFIKASILIST_EXCEPTION;
    private final static QName VERIFIKASILIST_QNAME = new QName("urn:verifikasilist", "verifikasilist");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/bpkad/eRetribusi/verifikasi.php?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VERIFIKASILIST_WSDL_LOCATION = url;
        VERIFIKASILIST_EXCEPTION = e;
    }

    public Verifikasilist() {
        super(__getWsdlLocation(), VERIFIKASILIST_QNAME);
    }

    public Verifikasilist(WebServiceFeature... features) {
        super(__getWsdlLocation(), VERIFIKASILIST_QNAME, features);
    }

    public Verifikasilist(URL wsdlLocation) {
        super(wsdlLocation, VERIFIKASILIST_QNAME);
    }

    public Verifikasilist(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VERIFIKASILIST_QNAME, features);
    }

    public Verifikasilist(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Verifikasilist(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VerifikasilistPortType
     */
    @WebEndpoint(name = "verifikasilistPort")
    public VerifikasilistPortType getVerifikasilistPort() {
        return super.getPort(new QName("urn:verifikasilist", "verifikasilistPort"), VerifikasilistPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerifikasilistPortType
     */
    @WebEndpoint(name = "verifikasilistPort")
    public VerifikasilistPortType getVerifikasilistPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:verifikasilist", "verifikasilistPort"), VerifikasilistPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VERIFIKASILIST_EXCEPTION!= null) {
            throw VERIFIKASILIST_EXCEPTION;
        }
        return VERIFIKASILIST_WSDL_LOCATION;
    }

}
